def get_indian_tickers():
    """
    Returns ~300 Top Indian Stocks (NSE 500 subset) + Gold + Bitcoin.
    """
    # --- Top 100 (Large Cap) ---
    large_cap = [
        "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "ICICIBANK.NS", "INFY.NS", "BHARTIARTL.NS", "ITC.NS", "SBIN.NS",
        "LICI.NS", "HINDUNILVR.NS", "LT.NS", "BAJFINANCE.NS", "HCLTECH.NS", "MARUTI.NS", "SUNPHARMA.NS", "ADANIENT.NS",
        "TATAMOTORS.NS", "ULTRACEMCO.NS", "AXISBANK.NS", "NTPC.NS", "TITAN.NS", "ONGC.NS", "KOTAKBANK.NS", "POWERGRID.NS",
        "ASIANPAINT.NS", "WIPRO.NS", "M&M.NS", "BAJAJFINSV.NS", "ADANIPORTS.NS", "COALINDIA.NS", "SIEMENS.NS",
        "NESTLEIND.NS", "SBILIFE.NS", "GRASIM.NS", "IOC.NS", "TECHM.NS", "HINDALCO.NS", "JSWSTEEL.NS", "BRITANNIA.NS",
        "TATASTEEL.NS", "INDUSINDBK.NS", "DIVISLAB.NS", "CIPLA.NS", "EICHERMOT.NS", "DRREDDY.NS", "BPCL.NS",
        "TATACONSUM.NS", "HEROMOTOCO.NS", "APOLLOHOSP.NS", "UPL.NS", "JIOFIN.NS", "HAL.NS", "DLF.NS", "BEL.NS",
        "VBL.NS", "TRENT.NS", "PIDILITIND.NS", "CHOLAFIN.NS", "GAIL.NS", "AMBUJACEM.NS", "BANKBARODA.NS", "HAVELLS.NS",
        "DABUR.NS", "ABB.NS", "GODREJCP.NS", "SHREECEM.NS", "CANBK.NS", "PNB.NS", "INDIGO.NS", "ICICIPRULI.NS",
        "TVSMOTOR.NS", "BOSCHLTD.NS", "MCDOWELL-N.NS", "NAUKRI.NS", "BERGEPAINT.NS", "MOTHERSON.NS", "POLYCAB.NS",
        "IRCTC.NS", "JUBLFOOD.NS", "MUTHOOTFIN.NS", "PIIND.NS", "ASTRAL.NS", "LTIM.NS", "PERSISTENT.NS", "MRF.NS",
        "ALKEM.NS", "MARICO.NS", "SRF.NS", "PAGEIND.NS", "BALKRISIND.NS", "CUMMINSIND.NS", "CONCOR.NS", "ASHOKLEY.NS"
    ]

    # --- Next 200 (Mid/Small Cap Leaders) ---
    mid_cap = [
        "OBEROIRLTY.NS", "TATACOMM.NS", "OFSS.NS", "ABCAPITAL.NS", "LALPATHLAB.NS", "MANYAVAR.NS", "WHIRLPOOL.NS",
        "ACC.NS", "AWL.NS", "APOLLOTYRE.NS", "ASHOKLEY.NS", "AUBANK.NS", "AUROPHARMA.NS", "BANDHANBNK.NS",
        "BATAINDIA.NS", "BHARATFORG.NS", "BIOCON.NS", "BSOFT.NS", "CHAMBLFERT.NS", "COFORGE.NS", "COLPAL.NS",
        "CROMPTON.NS", "DEEPAKNTR.NS", "DELTACORP.NS", "DIXON.NS", "ESCORTS.NS", "FEDERALBNK.NS", "GMRINFRA.NS",
        "GNFC.NS", "GODREJPROP.NS", "GRANULES.NS", "GUJGASLTD.NS", "HDFCAMC.NS", "HINDPETRO.NS", "IDFC.NS",
        "IDFCFIRSTB.NS", "IEX.NS", "IGL.NS", "INDHOTEL.NS", "INDIAMART.NS", "INDUSTOWER.NS", "IPCALAB.NS",
        "JKCEMENT.NS", "L&TFH.NS", "LAURUSLABS.NS", "LICHSGFIN.NS", "LUPIN.NS", "MANAPPURAM.NS", "MFSL.NS",
        "MGL.NS", "MPHASIS.NS", "NAM-INDIA.NS", "NAVINFLUOR.NS", "NMDC.NS", "OBEROIRLTY.NS", "PEL.NS", "PFC.NS",
        "PVRINOX.NS", "RBLBANK.NS", "RECLTD.NS", "SAIL.NS", "SYNGENE.NS", "TATACHEM.NS", "TATAPOWER.NS",
        "TORNTPOWER.NS", "TRENT.NS", "UBL.NS", "VOLTAS.NS", "ZEEL.NS", "ZYDUSLIFE.NS", "NHPC.NS", "RVNL.NS",
        "SJVN.NS", "IRFC.NS", "UNIONBANK.NS", "IOB.NS", "MAHABANK.NS", "UCOBANK.NS", "CENTRALBK.NS", "PSB.NS",
        "FACT.NS", "POONAWALLA.NS", "SUZLON.NS", "BSE.NS", "CDSL.NS", "MCX.NS", "ANGELONE.NS", "KALYANKJIL.NS",
        "KPITTECH.NS", "CYIENT.NS", "SONACOMS.NS", "UNOMINDA.NS", "JBCHEPHARM.NS", "GLENMARK.NS", "NATCOPHARM.NS",
        "PFIZER.NS", "SANOFI.NS", "ABFRL.NS", "DEVYANI.NS", "FLUOROCHEM.NS", "AIAENG.NS", "TIMKEN.NS", "SKFINDIA.NS",
        "THERMAX.NS", "SCHAEFFLER.NS", "KEI.NS", "KEC.NS", "KALPATPOWR.NS", "ELGIEQUIP.NS", "TRITURBINE.NS",
        "CARBORUNIV.NS", "GRINDWELL.NS", "KAJARIACER.NS", "CERA.NS", "CENTURYPLY.NS", "FINCABLES.NS", "VGUARD.NS",
        "REDINGTON.NS", "BSOFT.NS", "ZENSARTECH.NS", "SONATSOFTW.NS", "MASTEK.NS", "INTELLECT.NS", "TANLA.NS",
        "ROUTE.NS", "AFFLE.NS", "HAPPSTMNDS.NS", "LATENTVIEW.NS", "MAPMYINDIA.NS", "RATEGAIN.NS", "DATAPATTNS.NS",
        "MTARTECH.NS", "PARAS.NS", "ZENTECH.NS", "COCHINSHIP.NS", "MAZDOCK.NS", "GRSE.NS", "BDL.NS", "ASTRAMICRO.NS",
        "SOLARINDS.NS", "DYNAMATECH.NS", "CENTUM.NS", "ROSSARI.NS", "CLEAN.NS", "FINEORG.NS", "ALKYLAMINE.NS",
        "BALAMINES.NS", "LXCHEM.NS", "JUBLINGREA.NS", "GALAXYSURF.NS", "VINATIORGA.NS", "NOCIL.NS", "SUDARSCHEM.NS",
        "EPL.NS", "POLYPLEX.NS", "UFRLEX.NS", "SUPREMEIND.NS", "PRINCEPIPE.NS", "FINPIPE.NS", "APOLLOPIPES.NS",
        "JKPAPER.NS", "WESTCOASTP.NS", "ANDHRAPAP.NS", "SESHAPAPER.NS", "GREENPANEL.NS", "GREENPLY.NS", "STYRENIX.NS"
    ]
    
    global_assets = ["GC=F", "BTC-USD"] # Gold Futures, Bitcoin
    
    # Remove duplicates if any
    all_tickers = list(set(large_cap + mid_cap + global_assets))
    return all_tickers
